# Change these first
owner: neksodebe # Your GitHub organization or username, where this repository lives
repo: ntl-upptime # The name of this repository

sites:
  - name: Niko's TechLabs Website
    url: https://nikostechlabs.com/
    icon: https://gitlab.com/nikos-techlabs/assets/-/raw/main/ntl-vector.svg
  - name: Route Roulette
    url: https://routeroulette.xyz/
    icon: https://gitlab.com/nikos-techlabs/assets/-/raw/main/route-roulette/rr-256x256.png
  - name: Parottu - Landing page
    url: https://parottu.com/
    icon: https://gitlab.com/nikos-techlabs/assets/-/raw/main/parottu/parottu.svg

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.nikostechlabs.com
  # baseUrl: /your-repo-name
  logoUrl: https://gitlab.com/nikos-techlabs/assets/-/raw/main/ntl-vector.svg
  favicon: https://gitlab.com/nikos-techlabs/assets/-/raw/main/ntl-32x32.png
  faviconSvg: https://gitlab.com/nikos-techlabs/assets/-/raw/main/ntl-vector.svg
  name: niko's techlabs status
  introTitle: "welcome to the niko's techlabs status page"
  introMessage: this site monitors the status of all niko's techlabs projects, and the niko's techlabs website itself.
  navbar:
    - title: Status
      href: /
    - title: GitLab
      href: https://gitlab.com/nikos-techlabs/
  themeUrl: https://status.nikostechlabs.com/ntl-theme.css
  metaTags:
    - name: "title"
      content: "niko's techlabs status"
    - name: "description"
      content: "this site monitors the status of all niko's techlabs projects, and the niko's techlabs website itself."
    - name: "robots"
      content: "index follow"
    - name: "language"
      content: "English"
    - name: "author"
      content: "niko's techlabs"
    - name: "theme-color"
      content: "#8FFF94"
  customHeadHtml: |
    <meta property="og:title" content="niko's techlabs status">
    <meta property="og:type" content="website">
    <meta property="og:image" content="/ntl-256x256.png">
    <meta property="og:description" content="this site monitors the status of all niko's techlabs projects, and the niko's techlabs website itself.">

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
