# Change these first
owner: neksodebe # Your GitHub organization or username, where this repository lives
repo: ntl-upptime # The name of this repository

sites:
  - name: Niko's TechLabs Website
    url: https://nikostechlabs.com/
    icon: https://gitlab.com/nikos-techlabs/assets/-/raw/main/ntl-vector.svg
  - name: Route Roulette
    url: http://routeroulette.xyz/
    icon: https://gitlab.com/nikos-techlabs/assets/-/raw/main/route-roulette/rr-256x256.png
    port: 80
    check: "tcp-ping"
  - name: Parottu - Landing page
    url: https://parottu.com/
    icon: https://gitlab.com/nikos-techlabs/assets/-/raw/main/parottu/parottu.svg

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.nikostechlabs.com
  # baseUrl: /your-repo-name
  logoUrl: https://gitlab.com/nikos-techlabs/assets/-/raw/main/ntl-vector.svg
  name: niko's techlabs status
  introTitle: "welcome to the niko's techlabs status page"
  introMessage: niko's techlabs is a studio, focused on technology and especially programming. we usually make websites and applications, although we can really do anything.
  navbar:
    - title: Status
      href: /
    - title: GitLab
      href: https://gitlab.com/nikos-techlabs/
  theme: dark

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
